// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsWEGHYzCRaLP75DTulOVMBdJ1Uy813GM',
    appId: '1:547928856190:web:f42cee9b379ce9d2ac2a2f',
    messagingSenderId: '547928856190',
    projectId: 'crypto-wallet-4e256',
    authDomain: 'crypto-wallet-4e256.firebaseapp.com',
    storageBucket: 'crypto-wallet-4e256.appspot.com',
    measurementId: 'G-V69RWJJJPB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXExCzhsM3nPDLKsX05yMe1MmP5NgY1AM',
    appId: '1:547928856190:android:50a6ee6fdf4b90e7ac2a2f',
    messagingSenderId: '547928856190',
    projectId: 'crypto-wallet-4e256',
    storageBucket: 'crypto-wallet-4e256.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4M2pzom25cxmjbj2YKvHzazpOfAlWwSk',
    appId: '1:547928856190:ios:0dee434c6b4489c0ac2a2f',
    messagingSenderId: '547928856190',
    projectId: 'crypto-wallet-4e256',
    storageBucket: 'crypto-wallet-4e256.appspot.com',
    iosClientId: '547928856190-d1cep6s3qf4ncep1fj0j8atnr3sofch2.apps.googleusercontent.com',
    iosBundleId: 'com.example.pushNotification',
  );
}
